#read
GET http://localhost:80/read HTTP/1.1
#Create
# POST http://localhost:8080/registrarse HTTP/1.1
# Content-Type: application/json

# {
#   "no_documento":1033763510,
#   "primerNombre":"Otoniel",
#   "primerApellido":"Henández",
#   "segundoApellido":"Garzón",
#   "nombre_usuario":"OttoHernández",
#   "pais":"Colombia",
#   "telefono": 3218853192,
#   "correo": "otto@info.co",
#   "contraseña":"1234",
#   "rolesId":1,
#   "tipoDocumentoId":"1"
#   }