on:
  pull_request:
    types: [opened, closed]

jobs:
  update_card:
    runs-on: ubuntu-latest
    name: Updates Notion Card
    steps:
      - name: Updates to Code Review
        uses: ottohernandezgarzon/proyecto-tecsisline@testing
        with:
          page_property: 'Status'
          on_pr: 'Code Review 2'
          on_merge: 'Testing'
        env:
          NOTION_KEY: ${{ secrets.NOTIONKEY }} 
